"""add warehouses and inventory tracking

Revision ID: 4038b07d5100
Revises: 9e4bc72b6261
Create Date: 2026-07-31 16:48:07.225722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4038b07d5100'
down_revision: Union[str, Sequence[str], None] = '9e4bc72b6261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouses_name'), 'warehouses', ['name'], unique=True)
    op.create_table('inventory_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'warehouse_id', name='uq_inventory_product_warehouse')
    )
    op.create_index(op.f('ix_inventory_levels_product_id'), 'inventory_levels', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_levels_warehouse_id'), 'inventory_levels', ['warehouse_id'], unique=False)
    op.create_table('inventory_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('from_warehouse_id', sa.Integer(), nullable=False),
    sa.Column('to_warehouse_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('transferred_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['to_warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['transferred_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_transfers_from_warehouse_id'), 'inventory_transfers', ['from_warehouse_id'], unique=False)
    op.create_index(op.f('ix_inventory_transfers_product_id'), 'inventory_transfers', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_transfers_to_warehouse_id'), 'inventory_transfers', ['to_warehouse_id'], unique=False)
    op.create_index(op.f('ix_inventory_transfers_transferred_by_id'), 'inventory_transfers', ['transferred_by_id'], unique=False)
    # ### end Alembic commands ###

    # --- Hand-written data migration ---
    # Preserve each product's existing single-location quantity by moving it
    # into a "Main Warehouse" inventory_levels row before the old
    # products.current_quantity/warehouse_location columns are dropped below.
    warehouses_table = sa.table(
        "warehouses",
        sa.column("id", sa.Integer),
        sa.column("name", sa.String),
        sa.column("address", sa.Text),
    )
    connection = op.get_bind()
    main_warehouse_id = connection.execute(
        warehouses_table.insert()
        .values(name="Main Warehouse", address="Default location for stock migrated from Milestone 4.")
        .returning(warehouses_table.c.id)
    ).scalar_one()

    connection.execute(
        sa.text(
            """
            INSERT INTO inventory_levels (product_id, warehouse_id, quantity, created_at, updated_at)
            SELECT id, :warehouse_id, current_quantity, now(), now()
            FROM products
            """
        ),
        {"warehouse_id": main_warehouse_id},
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'current_quantity')
    op.drop_column('products', 'warehouse_location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    Note: this restores the old columns but NOT their values - quantities
    that were migrated into inventory_levels (and anything transferred
    since) aren't summed back into products.current_quantity. Acceptable
    for a downgrade path this early in the project; revisit if this ever
    needs to run against real production data.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('warehouse_location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('current_quantity', sa.INTEGER(), autoincrement=False, nullable=False, server_default='0'))
    op.drop_index(op.f('ix_inventory_transfers_transferred_by_id'), table_name='inventory_transfers')
    op.drop_index(op.f('ix_inventory_transfers_to_warehouse_id'), table_name='inventory_transfers')
    op.drop_index(op.f('ix_inventory_transfers_product_id'), table_name='inventory_transfers')
    op.drop_index(op.f('ix_inventory_transfers_from_warehouse_id'), table_name='inventory_transfers')
    op.drop_table('inventory_transfers')
    op.drop_index(op.f('ix_inventory_levels_warehouse_id'), table_name='inventory_levels')
    op.drop_index(op.f('ix_inventory_levels_product_id'), table_name='inventory_levels')
    op.drop_table('inventory_levels')
    op.drop_index(op.f('ix_warehouses_name'), table_name='warehouses')
    op.drop_table('warehouses')
    # ### end Alembic commands ###
